# Generated by Django 2.0 on 2017-06-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('body', models.CharField(max_length=100)),
                ('publisher', models.BigIntegerField()),
                ('create_by', models.BigIntegerField()),
                ('create_date', models.DateTimeField()),
                ('update_by', models.BigIntegerField()),
                ('update_date', models.DateTimeField()),
            ],
        ),
    ]
